version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    container_name: wepl-postgres
    environment:
      POSTGRES_USER: wepl_user
      POSTGRES_PASSWORD: wepl_password
      POSTGRES_DB: wepl_db
    ports:
      - "5432:5432"
    volumes:
      - wepl-db-data:/var/lib/postgresql/data

volumes:
  wepl-db-data:
